# Assignment 2: Bag of Words, TF-IDF, and Word2Vec

In [1]:
!pip install nltk scikit-learn gensim



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


## 1. Sample Data

In [2]:

documents = [
    "I love machine learning",
    "machine learning is powerful",
    "I love data science",
    "data science uses machine learning"
]


## 2. Bag of Words (Count Occurrence)

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
bow = cv.fit_transform(documents)

print("Vocabulary:")
print(cv.get_feature_names_out())

print("\nBoW Matrix:")
print(bow.toarray())


Vocabulary:
['data' 'is' 'learning' 'love' 'machine' 'powerful' 'science' 'uses']

BoW Matrix:
[[0 0 1 1 1 0 0 0]
 [0 1 1 0 1 1 0 0]
 [1 0 0 1 0 0 1 0]
 [1 0 1 0 1 0 1 1]]


## 3. Normalized Bag of Words

In [4]:
import numpy as np

bow_array = bow.toarray()
bow_l1 = bow_array / bow_array.sum(axis=1, keepdims=True)

print("\nL1 Normalized BoW:")
print(bow_l1)



L1 Normalized BoW:
[[0.         0.         0.33333333 0.33333333 0.33333333 0.
  0.         0.        ]
 [0.         0.25       0.25       0.         0.25       0.25
  0.         0.        ]
 [0.33333333 0.         0.         0.33333333 0.         0.
  0.33333333 0.        ]
 [0.2        0.         0.2        0.         0.2        0.
  0.2        0.2       ]]


In [5]:
from sklearn.preprocessing import normalize

bow_l2 = normalize(bow_array, norm='l2')

print("\nL2 Normalized BoW:")
print(bow_l2)



L2 Normalized BoW:
[[0.         0.         0.57735027 0.57735027 0.57735027 0.
  0.         0.        ]
 [0.         0.5        0.5        0.         0.5        0.5
  0.         0.        ]
 [0.57735027 0.         0.         0.57735027 0.         0.
  0.57735027 0.        ]
 [0.4472136  0.         0.4472136  0.         0.4472136  0.
  0.4472136  0.4472136 ]]


## 4. TF-IDF

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(documents)

print("\nTF-IDF Vocabulary:")
print(tfidf.get_feature_names_out())

print("\nTF-IDF Matrix:")
print(tfidf_matrix.toarray())



TF-IDF Vocabulary:
['data' 'is' 'learning' 'love' 'machine' 'powerful' 'science' 'uses']

TF-IDF Matrix:
[[0.         0.         0.53256952 0.65782931 0.53256952 0.
  0.         0.        ]
 [0.         0.59603894 0.38044393 0.         0.38044393 0.59603894
  0.         0.        ]
 [0.57735027 0.         0.         0.57735027 0.         0.
  0.57735027 0.        ]
 [0.45085176 0.         0.36500336 0.         0.36500336 0.
  0.45085176 0.57184829]]


## 5. Word2Vec Embeddings

In [7]:
import nltk
nltk.download('punkt')

from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec

tokenized_docs = [word_tokenize(doc.lower()) for doc in documents]

w2v_model = Word2Vec(
    sentences=tokenized_docs,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4
)

print("\nWord2Vec embedding for 'machine':")
print(w2v_model.wv['machine'])

print("\nWords similar to 'machine':")
print(w2v_model.wv.most_similar('machine'))


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\magdu\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!



Word2Vec embedding for 'machine':
[-8.6196875e-03  3.6657380e-03  5.1898835e-03  5.7419385e-03
  7.4669183e-03 -6.1676754e-03  1.1056137e-03  6.0472824e-03
 -2.8400505e-03 -6.1735227e-03 -4.1022300e-04 -8.3689485e-03
 -5.6000124e-03  7.1045388e-03  3.3525396e-03  7.2256695e-03
  6.8002474e-03  7.5307419e-03 -3.7891543e-03 -5.6180597e-04
  2.3483764e-03 -4.5190323e-03  8.3887316e-03 -9.8581640e-03
  6.7646410e-03  2.9144168e-03 -4.9328315e-03  4.3981876e-03
 -1.7395747e-03  6.7113843e-03  9.9648498e-03 -4.3624435e-03
 -5.9933780e-04 -5.6956373e-03  3.8508223e-03  2.7866268e-03
  6.8910765e-03  6.1010956e-03  9.5384968e-03  9.2734173e-03
  7.8980681e-03 -6.9895042e-03 -9.1558648e-03 -3.5575271e-04
 -3.0998408e-03  7.8943167e-03  5.9385742e-03 -1.5456629e-03
  1.5109634e-03  1.7900408e-03  7.8175711e-03 -9.5101865e-03
 -2.0553112e-04  3.4691966e-03 -9.3897223e-04  8.3817719e-03
  9.0107834e-03  6.5365066e-03 -7.1162102e-04  7.7104042e-03
 -8.5343346e-03  3.2071066e-03 -4.6379971e-03 -5.0